### ISSUE TITLE
ERROR TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by lukaszlenart** [johnpduane/confluence-api#3]
On Heroku I get the above error, the whole stacktrace looks like this:

```
[Fri Apr 22 2016 11:42:28 GMT+0200 (CEST)] ERROR TypeError: Cannot read property 'body' of undefined
  at /app/node_modules/confluence-api/lib/confluence.js:162:34
  at Request.callback (/app/node_modules/confluence-api/node_modules/superagent/lib/node/index.js:687:12)
  at ClientRequest.<anonymous> (/app/node_modules/confluence-api/node_modules/superagent/lib/node/index.js:639:10)
  at CleartextStream.read [as _read] (tls.js:472:13)
  at ClientRequest.emit (events.js:95:17)
  at SecurePair.emit (events.js:92:17)
  at CleartextStream.socketErrorListener (http.js:1603:9)
  at CleartextStream.emit (events.js:95:17)
  at SecurePair.<anonymous> (tls.js:1400:19)
  at CleartextStream.Readable.read (_stream_readable.js:341:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at SecurePair.maybeInitFinished (tls.js:980:10)
  at doWrite (_stream_writable.js:226:10)
  at EncryptedStream.Writable.write (_stream_writable.js:183:11)
  at EncryptedStream.write [as _write] (tls.js:369:25)
  at write (_stream_readable.js:602:24)
  at flow (_stream_readable.js:611:7)
  at emitReadable_ (_stream_readable.js:427:10)
  at Socket.pipeOnReadable (_stream_readable.js:643:5)
  at emitReadable (_stream_readable.js:423:5)
  at Socket.emit (events.js:92:17)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)      
```

The same code works without problems locally, any idea what can be wrong?

**Comment by johnpduane** [comment]
It looks like the error is in the createPage function. I will add a check to be sure res.body is not undefined before accessing it so the library does not bomb! In the interim, my advice is to:
- Check to be sure your config has a valid username and password for the baseUrl you are using;
- Check to be sure the username has create page privileges at the baseUrl you are using;
- Set a breakpoint at line 162 and inspect `err` to see a more detailed description of the error.

Sorry you ran into this.

**Comment by lukaszlenart** [comment]
Thanks! The problem was different, I was using an old version of `node` which has had an issue with SSL and that was the main reason, instead of proper response from Confluence I was getting:
`ERROR [Error: CERT_UNTRUSTED]`
